#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

# Keyboard configuration.
setxkbmap -model abnt2 -layout br -option

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# Monitor configuration.
xrandr --output DP-2 --mode 1920x1080 --rate 165
xrandr --output HDMI-0 --auto --left-of DP-2

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

# Status bar.
while true
do
  LOCALTIME=$(date "+%H:%M")
  WIFI=$(iw dev wlp7s0 link | grep SSID | cut -c8-)
  xsetroot -name " $WIFI - $LOCALTIME"
  sleep 20s
done &
# Right alt to accentuation.
# setxkbmap -option compose:ralt &
# No composition ralt.
# setxkbmap -model abnt2 -layout br -option &
# setxkbmap -model pc105 -layout br -option &
# st &

# chromium &
st -e tmux &
exec dwm
