#!/bin/sh

userresources=$HOME/.Xresources
usermodmap=$HOME/.Xmodmap
sysresources=/etc/X11/xinit/.Xresources
sysmodmap=/etc/X11/xinit/.Xmodmap

# merge in defaults and keymaps
if [ -f $sysresources ]; then
    xrdb -merge $sysresources
fi

if [ -f $sysmodmap ]; then
    xmodmap $sysmodmap
fi

# Keyboard configuration.
setxkbmap -model abnt2 -layout br -option

if [ -f "$userresources" ]; then
    xrdb -merge "$userresources"
fi

if [ -f "$usermodmap" ]; then
    xmodmap "$usermodmap"
fi

# Monitor configuration.
# xrandr --output DP-2 --mode 1920x1080 --rate 165
# xrandr --output HDMI-0 --auto --left-of DP-2
xrandr --output HDMI1 --auto --left-of eDP1

# start some nice programs
if [ -d /etc/X11/xinit/xinitrc.d ] ; then
    for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
        [ -x "$f" ] && . "$f"
    done
    unset f
fi

# # Status bar.
# while true
# do
# LOCALTIME=$(date "+%H:%M")
# WIFI=$(iw dev wlp7s0 link | grep SSID | cut -c8-)
# xsetroot -name " $WIFI - $LOCALTIME"
# sleep 20s
# done &

# Status bar.
while true
do
    BATTERY=$(acpi -i | head -1 | cut -f2 -d,)
    LOCALTIME=$(date "+%H:%M")
    # Have a wifi connection.
    WIFI=$(iw dev wlo1 link | grep SSID | cut -c8-)
    if [ ! -z "$WIFI" ]; then
        xsetroot -name "$BATTERY - $WIFI - $LOCALTIME"
    else
        # Have a wired connection.
        WIRED=$(ip a | grep enp5s0 | grep LOWER_UP)
        if [ ! -z "$WIRED" ]; then
            xsetroot -name "$BATTERY - Wired - $LOCALTIME"
        # No wired connection.
        else
            xsetroot -name "$BATTERY - $LOCALTIME"
        fi
    fi
    sleep 20s
    done &

# Right alt to accentuation.
# setxkbmap -option compose:ralt &
# No composition ralt.
# setxkbmap -model abnt2 -layout br -option &
# setxkbmap -model pc105 -layout br -option &
# st &

# chromium &
st -e tmux &
exec dwm
